language: cpp

os:
  - linux

compiler:
  # - clang # disabled clang due to missing libc++
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
  - "mkdir -p $TRAVIS_BUILD_DIR/build/scripts"
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  - "cmake $TRAVIS_BUILD_DIR"

script:
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  - "make -j3"
  # test compile-time constraints
  - "make test_sqlpp_constraints"

