language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  - CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

install:
  - CMAKE_VERSION_MM=3.2
  - CMAKE_VERSION_FULL=$CMAKE_VERSION_MM.2
  - git clone https://github.com/HowardHinnant/date
  - cd date
  - git checkout tags/v1.0.0
  - cd ..
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      && sudo add-apt-repository -y ppa:apokluda/boost1.53
      && sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
      && sudo apt-get update -qq
      && sudo apt-get update -qq
      && sudo apt-get install -qq g++-4.8 libboost1.53-dev --no-install-recommends
      && sudo apt-get install -qq -y g++-4.9 cmake cmake-data
      ;
    fi

before_script:
   - mkdir build
   - cd build
   - if [[ "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then
         cp -r ../scripts/ . &&
         cp -r ../test_scripts/ . &&
         sudo apt-get install python-pyparsing;
     fi
   - if [[ "$CXX" = "g++" && "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then export CXXFLAGS="--coverage"; fi
   - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=$PWD/../date

script:
   - cmake --build . --config $CONFIG
   - ctest --output-on-failure

after_script:
  - ../coveralls
